name: Code Coverage Report
description: Insert a runner check containing coverage report
author: LordLyng
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  minimum-coverage-percentage:
    description: indicates a value for wat coverage percentage will be required for the check to pass
    required: false
  name:
    description: Name of the check run
    required: true
runs:
  using: node12
  main: dist/main.js
